name: Pull Request

on:
  pull_request:
    branches: [ "main" ]
jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6' # Specify your Go version
      - name: Install Dependencies
        working-directory: atlas.com/<%= resourceName %>
        run: go mod download
      - name: Build the Go Application
        working-directory: atlas.com/<%= resourceName %>
        run: go build -v ./...
      - name: Run Tests
        working-directory: atlas.com/<%= resourceName %>
        run: go test -v ./...
